### ISSUE TITLE
`serial_test_import_glb` rust test is flaky

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2396]
when the rust tests fail its usually becuase of this test, which is weird since it passes sometimes too

not the biggest priority but want to rule out its a symptom of something bigger, cc @alteous

**Comment by jessfraz** [comment]
it might just be we've changed the format and need to update the file idk

**Comment by alteous** [comment]
It looks like it has something to do with the websocket timing out:

```
david@kittycad:~/kc-repos/modeling-app/src/wasm-lib$ cargo test import
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/david/kc-repos/modeling-app/src/wasm-lib/kcl/Cargo.toml
workspace: /home/david/kc-repos/modeling-app/src/wasm-lib/Cargo.toml
    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running unittests src/lib.rs (target/debug/deps/wasm_lib-9de5fe303678f21e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/executor/main.rs (target/debug/deps/executor-9933be4422ced090)

running 8 tests
test serial_test_import_file_doesnt_exist ... ok
test serial_test_import_ext_doesnt_match ... ok
test serial_test_import_obj_with_mtl_units ... FAILED
test serial_test_import_gltf_embedded ... ok
test serial_test_import_gltf_with_bin ... ok
test serial_test_import_glb_no_assign ... ok
test serial_test_import_obj_with_mtl ... ok
test serial_test_import_glb ... ok

failures:

---- serial_test_import_obj_with_mtl_units stdout ----
Current working directory: "/home/david/kc-repos/modeling-app/src/wasm-lib"
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_import_obj_with_mtl_units' panicked at tests/executor/main.rs:1143:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([14, 81])], message: "Modeling command failed: websocket closed early" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    serial_test_import_obj_with_mtl_units

test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured; 83 filtered out; finished in 6.06s

error: test failed, to rerun pass `--test executor`
```
```
david@kittycad:~/kc-repos/modeling-app/src/wasm-lib$ cargo test import
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/david/kc-repos/modeling-app/src/wasm-lib/kcl/Cargo.toml
workspace: /home/david/kc-repos/modeling-app/src/wasm-lib/Cargo.toml
    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running unittests src/lib.rs (target/debug/deps/wasm_lib-9de5fe303678f21e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/executor/main.rs (target/debug/deps/executor-9933be4422ced090)

running 8 tests
test serial_test_import_file_doesnt_exist ... ok
test serial_test_import_ext_doesnt_match ... ok
test serial_test_import_glb_no_assign ... FAILED
test serial_test_import_gltf_with_bin ... FAILED
test serial_test_import_gltf_embedded ... ok
test serial_test_import_obj_with_mtl_units ... ok
test serial_test_import_glb ... ok
test serial_test_import_obj_with_mtl ... ok

failures:

---- serial_test_import_glb_no_assign stdout ----
Current working directory: "/home/david/kc-repos/modeling-app/src/wasm-lib"
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_import_glb_no_assign' panicked at tests/executor/main.rs:1183:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([0, 40])], message: "Modeling command failed: websocket closed early" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- serial_test_import_gltf_with_bin stdout ----
Current working directory: "/home/david/kc-repos/modeling-app/src/wasm-lib"
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_import_gltf_with_bin' panicked at tests/executor/main.rs:1153:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([14, 55])], message: "Modeling command failed: websocket closed early" }


failures:
    serial_test_import_glb_no_assign
    serial_test_import_gltf_with_bin

test result: FAILED. 6 passed; 2 failed; 0 ignored; 0 measured; 83 filtered out; finished in 5.11s

error: test failed, to rerun pass `--test executor`
```

**Comment by alteous** [comment]
It looks like lots of other tests are failing with the same cause:
```
david@kittycad:~/kc-repos/modeling-app/src/wasm-lib$ cargo test
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/david/kc-repos/modeling-app/src/wasm-lib/kcl/Cargo.toml
workspace: /home/david/kc-repos/modeling-app/src/wasm-lib/Cargo.toml
    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running unittests src/lib.rs (target/debug/deps/wasm_lib-9de5fe303678f21e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/executor/main.rs (target/debug/deps/executor-9933be4422ced090)

running 91 tests
test serial_test_cube_mm ... FAILED
test serial_test_big_number_angle_to_match_length_y ... FAILED
test serial_test_cube_yd ... FAILED
test serial_test_cube_ft ... FAILED
test serial_test_close_arc ... FAILED
test serial_test_basic_fillet_cube_start ... FAILED
test serial_test_basic_revolve_circle ... FAILED
test serial_test_big_number_angle_to_match_length_x ... FAILED
test serial_test_basic_tangential_arc_with_point ... FAILED
test serial_test_basic_tangential_arc_to ... FAILED
test serial_test_bracket_with_fillets_ensure_fail_on_flush_source_ranges ... ok
test serial_test_execute_pipes_on_pipes ... ignored
test serial_test_basic_fillet_cube_previous_adjacent ... FAILED
test serial_test_cube_in ... FAILED
test serial_test_execute_kittycad_svg ... FAILED
test serial_test_error_sketch_on_arc_face ... ok
test serial_test_execute_engine_error_return ... ok
test serial_test_execute_with_angled_line ... FAILED
test serial_test_empty_file_is_ok ... ok
test serial_test_execute_parametric_with_tan_arc_example ... FAILED
test serial_test_basic_tangential_arc ... ok
test serial_test_cube_cm ... ok
test serial_test_import_file_doesnt_exist ... ok
test serial_test_import_ext_doesnt_match ... ok
test serial_test_basic_fillet_cube_next_adjacent ... ok
test optional_params ... ok
test serial_test_fillet_duplicate_tags ... ok
test serial_test_basic_fillet_cube_close_opposite ... ok
test serial_test_basic_fillet_cube_end ... ok
test serial_test_cube_m ... ok
test serial_test_dimensions_match ... ok
test serial_test_execute_cylinder ... ok
test serial_test_execute_i_shape ... ok
test serial_test_execute_parametric_example ... ok
test serial_test_different_planes_same_drawing ... ok
test serial_test_execute_with_function_sketch ... ok
test serial_test_execute_with_function_sketch_with_position ... ok
test serial_test_helix_ccw ... ok
test serial_test_helix_with_length ... ok
test serial_test_holes ... ok
test serial_test_helix_defaults ... ok
test serial_test_helix_defaults_negative_extrude ... ok
test serial_test_import_glb ... ok
test serial_test_import_obj_with_mtl ... ok
test serial_test_import_glb_no_assign ... ok
test serial_test_import_gltf_embedded ... ok
test serial_test_import_gltf_with_bin ... ok
test serial_test_import_obj_with_mtl_units ... ok
test serial_test_lots_of_planes ... ok
test serial_test_patterns_linear_basic_negative_distance ... FAILED
test serial_test_member_expression_in_params ... ok
test serial_test_member_expression_sketch_group ... ok
test serial_test_revolve_bad_angle_low ... FAILED
test serial_test_patterns_circular_3d_tilted_axis ... ok
test serial_test_plumbus_fillets ... FAILED
test serial_test_revolve_on_edge_get_edge ... FAILED
test serial_test_negative_args ... ok
test serial_test_revolve_bad_angle_high ... ok
test serial_test_revolve_on_face_circle_edge ... FAILED
test serial_test_patterns_circular_basic_3d ... ok
test serial_test_mike_stress_lines ... ok
test serial_test_patterns_linear_basic_3d ... ok
test serial_test_patterns_linear_basic_holes ... ok
test serial_test_patterns_circular_basic_2d ... ok
test serial_test_patterns_linear_basic ... ok
test serial_test_pentagon_fillet_sugar ... ok
test serial_test_pentagon_fillet_desugar ... ok
test serial_test_patterns_linear_basic_negative_axis ... ok
test serial_test_revolve_on_edge ... ok
test serial_test_patterns_linear_basic_with_math ... ok
test serial_test_revolve_on_face ... ok
test serial_test_revolve_on_face_circle ... ok
test serial_test_rounded_with_holes ... ok
test serial_test_simple_revolve_custom_angle ... ok
test serial_test_simple_revolve ... ok
test serial_test_stdlib_kcl_error_circle ... ok
test serial_test_riddle_small ... ok
test serial_test_simple_revolve_custom_axis ... ok
test serial_test_stdlib_kcl_error_right_code_path ... ok
test serial_test_simple_revolve_negative ... ok
test serial_test_simple_revolve_sketch_on_edge ... ok
test serial_test_sketch_on_face ... ok
test serial_test_simple_revolve_uppercase ... ok
test serial_test_sketch_on_face_circle ... ok
test serial_test_sketch_on_face_end ... ok
test serial_test_sketch_on_face_circle_tagged ... ok
test serial_test_sketch_on_face_end_negative_extrude ... ok
test serial_test_sketch_on_face_start ... ok
test serial_test_sketch_on_face_of_face ... ok
test serial_test_lego ... ok
test serial_test_top_level_expression ... ok

failures:

---- serial_test_cube_mm stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_cube_mm' panicked at tests/executor/main.rs:1218:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([41, 60])], message: "Modeling command failed: websocket closed early" }

---- serial_test_big_number_angle_to_match_length_y stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_big_number_angle_to_match_length_y' panicked at tests/executor/main.rs:1565:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([16, 35])], message: "Modeling command failed: websocket closed early" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- serial_test_cube_yd stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_cube_yd' panicked at tests/executor/main.rs:1333:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([41, 60])], message: "Modeling command failed: websocket closed early" }

---- serial_test_cube_ft stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_cube_ft' panicked at tests/executor/main.rs:1310:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([41, 60])], message: "Modeling command failed: websocket closed early" }

---- serial_test_close_arc stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_close_arc' panicked at tests/executor/main.rs:692:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([70, 89])], message: "Modeling command failed: websocket closed early" }

---- serial_test_basic_fillet_cube_start stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_basic_fillet_cube_start' panicked at tests/executor/main.rs:286:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([16, 35])], message: "Modeling command failed: websocket closed early" }

---- serial_test_basic_revolve_circle stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_basic_revolve_circle' panicked at tests/executor/main.rs:1876:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([18, 37])], message: "Modeling command failed: websocket closed early" }

---- serial_test_big_number_angle_to_match_length_x stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_big_number_angle_to_match_length_x' panicked at tests/executor/main.rs:1542:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([16, 35])], message: "Modeling command failed: websocket closed early" }

---- serial_test_basic_tangential_arc_with_point stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_basic_tangential_arc_with_point' panicked at tests/executor/main.rs:750:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([18, 39])], message: "Modeling command failed: websocket closed early" }

---- serial_test_basic_tangential_arc_to stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_basic_tangential_arc_to' panicked at tests/executor/main.rs:765:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([18, 39])], message: "Modeling command failed: websocket closed early" }

---- serial_test_basic_fillet_cube_previous_adjacent stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_basic_fillet_cube_previous_adjacent' panicked at tests/executor/main.rs:368:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([16, 35])], message: "Modeling command failed: websocket closed early" }

---- serial_test_cube_in stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_cube_in' panicked at tests/executor/main.rs:1287:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([41, 60])], message: "Modeling command failed: websocket closed early" }

---- serial_test_execute_kittycad_svg stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_execute_kittycad_svg' panicked at tests/executor/main.rs:565:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([12, 31])], message: "Modeling command failed: websocket closed early" }

---- serial_test_execute_with_angled_line stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_execute_with_angled_line' panicked at tests/executor/main.rs:440:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([16, 35])], message: "Modeling command failed: websocket closed early" }

---- serial_test_execute_parametric_with_tan_arc_example stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_execute_parametric_with_tan_arc_example' panicked at tests/executor/main.rs:504:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([301, 322])], message: "Modeling command failed: websocket closed early" }

---- serial_test_patterns_linear_basic_negative_distance stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_patterns_linear_basic_negative_distance' panicked at tests/executor/main.rs:1012:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([13, 32])], message: "Modeling command failed: websocket closed early" }

---- serial_test_revolve_bad_angle_low stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_revolve_bad_angle_low' panicked at tests/executor/main.rs:1658:5:
assertion `left == right` failed
  left: "engine: KclErrorDetails { source_ranges: [SourceRange([16, 35])], message: \"Modeling command failed: websocket closed early\" }"
 right: "semantic: KclErrorDetails { source_ranges: [SourceRange([278, 314])], message: \"Expected angle to be between -360 and 360, found `-455`\" }"

---- serial_test_plumbus_fillets stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_plumbus_fillets' panicked at tests/executor/main.rs:1968:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([307, 326])], message: "Modeling command failed: websocket closed early" }

---- serial_test_revolve_on_edge_get_edge stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_revolve_on_edge_get_edge' panicked at tests/executor/main.rs:1782:5:
assertion `left == right` failed
  left: "engine: KclErrorDetails { source_ranges: [SourceRange([12, 31])], message: \"Modeling command failed: websocket closed early\" }"
 right: "engine: KclErrorDetails { source_ranges: [SourceRange([349, 409])], message: \"Modeling command failed: Some([ApiError { error_code: InternalEngine, message: \\\"Solid3D revolve failed:  sketch profile must lie entirely on one side of the revolution axis\\\" }])\" }"

---- serial_test_revolve_on_face_circle_edge stdout ----
got error message: {
  "error_code": "bad_request",
  "message": "Too many active connections, only 2 allowed per user."
}
got ws error: WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
thread 'serial_test_revolve_on_face_circle_edge' panicked at tests/executor/main.rs:1808:10:
called `Result::unwrap()` on an `Err` value: engine: KclErrorDetails { source_ranges: [SourceRange([12, 31])], message: "Modeling command failed: websocket closed early" }


failures:
    serial_test_basic_fillet_cube_previous_adjacent
    serial_test_basic_fillet_cube_start
    serial_test_basic_revolve_circle
    serial_test_basic_tangential_arc_to
    serial_test_basic_tangential_arc_with_point
    serial_test_big_number_angle_to_match_length_x
    serial_test_big_number_angle_to_match_length_y
    serial_test_close_arc
    serial_test_cube_ft
    serial_test_cube_in
    serial_test_cube_mm
    serial_test_cube_yd
    serial_test_execute_kittycad_svg
    serial_test_execute_parametric_with_tan_arc_example
    serial_test_execute_with_angled_line
    serial_test_patterns_linear_basic_negative_distance
    serial_test_plumbus_fillets
    serial_test_revolve_bad_angle_low
    serial_test_revolve_on_edge_get_edge
    serial_test_revolve_on_face_circle_edge

test result: FAILED. 70 passed; 20 failed; 1 ignored; 0 measured; 0 filtered out; finished in 16.21s

error: test failed, to rerun pass `--test executor`
```

**Comment by alteous** [comment]
If the websocket is timing out, it's unsurprising that it would do so when importing geometry because that can be a slow operation.

**Comment by jessfraz** [comment]
you arent running them serially, so yes the websocket is timing out for that one but it didn't before and thats the weird thing... like is it a symptom of something else it has 60 seconds to import the file, that seems excessive

**Comment by jessfraz** [comment]
also get this quite often
```
Current working directory: "/home/runner/work/modeling-app/modeling-app/src/wasm-lib"
got ws error: WebSocket protocol error: Connection reset without closing handshake
Caused by:
    Connection reset without closing handshake
test serial_test_import_glb ... FAILED
```

that means the server is closing it not us... i just think something is suspicious

**Comment by jessfraz** [comment]
another fun fact, you can run against a local engine w LOCAL_ENGINE_ADDR=http://system76-pc:8080 but like point to yours haha

**Comment by alteous** [comment]
I'm not able to reproduce this locally anymore. Is this still a problem?

**Comment by jessfraz** [comment]
these seem less flakey now
