### ISSUE TITLE
Error on bad model

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3251]
Sorry Im rushing here

Try this

```
const sketch2 = startSketchOn("XY")
const sketch001 = startSketchAt([-0, -0])
  |> line([0, 0], %)
  |> line([-4.84, -5.29], %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
```

look at dev console

bad stuff

**Comment by lf94** [comment]
@Irev-Dev maybe caused by new artifact map usage

**Comment by jessfraz** [comment]
yeah the error has artifact map in it
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at getArtifactsToUpdate (index-CxhYpFkn.js:4221:102424)
    at index-CxhYpFkn.js:4221:100440
    at Array.forEach (<anonymous>)
    at createArtifactGraph (index-CxhYpFkn.js:4221:100230)
    at EngineCommandManager.waitForAllCommands (index-CxhYpFkn.js:4225:14177)
    at async KclManager.executeAst (index-CxhYpFkn.js:4226:169142)
    ```

**Comment by Irev-Dev** [comment]
got https://github.com/KittyCAD/modeling-app/pull/3269 up, with a test

Found a cryptic error while solving this one
https://github.com/KittyCAD/modeling-app/issues/3268
