### ISSUE TITLE
Add a basic tauri e2e test on Linux

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#684]
https://tauri.app/v1/guides/testing/webdriver/introduction/

**Comment by pierremtb** [comment]
Getting back to this. Cloning and compiling https://github.com/chippers/hello_tauri works, but I hit a bump when trying to run the e2e test

```
PS D:\Users\pierre_win10\Documents\hello_tauri\webdriver\webdriverio> yarn wdio run w
dio.conf.js
yarn run v1.22.19
$ D:\Users\pierre_win10\Documents\hello_tauri\webdriver\node_modules\.bin\wdio run wd
io.conf.js

Execution of 1 workers started at 2023-10-11T13:36:44.409Z

2023-10-11T13:36:44.435Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-10-11T13:36:45.196Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-10-11T13:36:45.198Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio
.conf.js
[0-0] 2023-10-11T13:36:46.298Z INFO @wdio/local-runner: Run worker command: run
[0-0] Starting Microsoft Edge WebDriver 117.0.2045.41 (b895513e980748a14404cb2144b57c
923254c535) on port 4445
[0-0] To submit feedback, report a bug, or suggest new features, please visit https:/
/github.com/MicrosoftEdge/EdgeWebDriver
[0-0]
[0-0] Only local connections are allowed.
[0-0] Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsof
t Edge WebDriver safe.
[0-0]
[0-0] Microsoft Edge WebDriver was started successfully.
[0-0] RUNNING in undefined - D:\Users\pierre_win10\Documents\hello_tauri\webdriver\we
bdriverio\test\specs\example.e2e.js
[0-0] 2023-10-11T13:36:46.636Z INFO webdriver: Initiate new session using the WebDriv
er protocol
[0-0] 2023-10-11T13:36:46.721Z INFO webdriver: [POST] http://localhost:4444/session
[0-0] 2023-10-11T13:36:46.721Z INFO webdriver: DATA {
[0-0]   capabilities: { alwaysMatch: { 'tauri:options': [Object] }, firstMatch: [ {}
] },
[0-0]   desiredCapabilities: {
[0-0]     'tauri:options': { application: '../../target/release/hello_tauri' }
[0-0]   }
[0-0] }
[0-0] 2023-10-11T13:36:46.749Z ERROR webdriver: RequestError: connect ECONNREFUSED ::
1:4444
[0-0]     at ClientRequest.<anonymous> (D:\Users\pierre_win10\Documents\hello_tauri\w
ebdriver\node_modules\got\dist\source\core\index.js:956:111)
[0-0]     at Object.onceWrapper (node:events:632:26)
[0-0]     at ClientRequest.emit (node:events:529:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at origin.emit (D:\Users\pierre_win10\Documents\hello_tauri\webdriver\node_
modules\@szmarczak\http-timer\dist\source\index.js:43:20)
[0-0]     at Socket.socketErrorListener (node:_http_client:501:9)
[0-0]     at Socket.emit (node:events:517:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
[0-0] 2023-10-11T13:36:46.749Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:4444/", make sure browser driver is runn
ing on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in w
dio.log file as the service might had problems to start the driver.
[0-0]     at Object.startWebDriverSession (D:\Users\pierre_win10\Documents\hello_taur
i\webdriver\node_modules\webdriver\build\utils.js:68:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (D:\Users\pierre_win10\Documents\hello_tauri\webdriver\node_modules\webdriver\build\index.js:58:45)
[0-0]     at async Object.remote (D:\Users\pierre_win10\Documents\hello_tauri\webdriver\node_modules\@wdio\runner\node_modules\webdriverio\build\index.js:67:22)
[0-0]     at async Runner._startSession (D:\Users\pierre_win10\Documents\hello_tauri\webdriver\node_modules\@wdio\runner\build\index.js:216:56)
[0-0]     at async Runner._initSession (D:\Users\pierre_win10\Documents\hello_tauri\webdriver\node_modules\@wdio\runner\build\index.js:172:25)
[0-0]     at async Runner.run (D:\Users\pierre_win10\Documents\hello_tauri\webdriver\node_modules\@wdio\runner\build\index.js:87:19)
[0-0] FAILED in undefined - D:\Users\pierre_win10\Documents\hello_tauri\webdriver\webdriverio\test\specs\example.e2e.js
2023-10-11T13:36:46.874Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:02

2023-10-11T13:36:46.876Z INFO @wdio/local-runner: Shutting down spawned worker
2023-10-11T13:36:47.131Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-10-11T13:36:47.133Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I can go a little further when forcing `port: 4445` in the config, with Edge opening up, but it doesn't seem to connect to the webserver in the tauri app and the test fails. From what I read there should be two workers running at 4444 and 4445, so that hack to get passed the first error isn't the right way to go

Found this repo which has tests for Linux and Windows, in a Github Actions so I'm hopeful still https://github.com/Orbitale/Compotes/blob/rewrite/.github/workflows/main.yaml

Will get back at it tomorrow

**Comment by pierremtb** [comment]
Yesterday I tried to run all the steps in https://github.com/Orbitale/Compotes/blob/rewrite/.github/workflows/main.yaml on my Windows machine, but I still hit the same issue `ERROR webdriver: RequestError: connect ECONNREFUSED ::
1:4444`

I really think it has to do with my setup now, will investigate more today

**Comment by pierremtb** [comment]
Crap, just realized that the tests at https://github.com/Orbitale/Compotes/actions/runs/5800518345/job/15722791031, despite reporting green, are actually failing 😢 However on their side it doesn't complain about 4444 🤫

**Comment by pierremtb** [comment]
Created https://github.com/KittyCAD/hello_tauri, as they seem to have a webdriverio config that works for real on windows-latest, and I want to see it run live today (last build is 3m on their repo)

**Comment by pierremtb** [comment]
Scratch that I'm stupid, that successful test in their repo is on ubuntu-latest not windows-latest. Trying the same commands on Windows again, pretty sure I tried it already tho 🤷
